[mcp_servers.supabase]
  url = "https://mcp.supabase.com/mcp?project_ref=ijcocumeslxoujvtjflf&features=docs%2Cdatabase%2Cdebugging"

[mcp_servers.sentry]
  url = "https://mcp.sentry.dev/mcp/smallerworld/smallerworld_v2"
