# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activerecord-postgis-adapter` gem.
# Please instead update this file by running `bin/tapioca gem activerecord-postgis-adapter`.


# :startdoc:
#
# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/version.rb#3
module ActiveRecord; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/version.rb#4
module ActiveRecord::ConnectionAdapters; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/version.rb#5
module ActiveRecord::ConnectionAdapters::PostGIS; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#9
class ActiveRecord::ConnectionAdapters::PostGIS::Column < ::ActiveRecord::ConnectionAdapters::PostgreSQL::Column
  # sql_type examples:
  #   "Geometry(Point,4326)"
  #   "Geography(Point,4326)"
  #
  # @return [Column] a new instance of Column
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#10
  def initialize(name, cast_type, default, sql_type_metadata = T.unsafe(nil), null = T.unsafe(nil), default_function = T.unsafe(nil), collation: T.unsafe(nil), comment: T.unsafe(nil), serial: T.unsafe(nil), generated: T.unsafe(nil), spatial: T.unsafe(nil), identity: T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#80
  def ==(other); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#70
  def encode_with(coder); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#90
  def eql?(other); end

  # Returns the value of attribute geographic.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#42
  def geographic; end

  # Returns the value of attribute geographic.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#48
  def geographic?; end

  # Returns the value of attribute geometric_type.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#42
  def geometric_type; end

  # Returns the value of attribute has_m.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#42
  def has_m; end

  # Returns the value of attribute has_m.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#50
  def has_m?; end

  # Returns the value of attribute has_z.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#42
  def has_z; end

  # Returns the value of attribute has_z.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#49
  def has_z?; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#92
  def hash; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#60
  def init_with(coder); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#52
  def limit; end

  # @return [Boolean]
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#56
  def spatial?; end

  # Returns the value of attribute srid.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#42
  def srid; end

  private

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#109
  def build_from_sql_type(sql_type); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#105
  def set_geometric_type_from_name(name); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column.rb#114
  def to_type_name(geometric_type); end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_table_definition.rb#36
module ActiveRecord::ConnectionAdapters::PostGIS::ColumnDefinitionUtils
  class << self
    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_table_definition.rb#53
    def default_srid(options); end

    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_table_definition.rb#38
    def geo_type(type = T.unsafe(nil)); end

    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_table_definition.rb#45
    def limit_from_options(type, options = T.unsafe(nil)); end
  end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#6
module ActiveRecord::ConnectionAdapters::PostGIS::ColumnMethods
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#13
  def geography(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#17
  def geometry(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#21
  def geometry_collection(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#25
  def line_string(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#29
  def multi_line_string(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#33
  def multi_point(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#37
  def multi_polygon(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#8
  def spatial(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#41
  def st_point(name, options = T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#45
  def st_polygon(name, options = T.unsafe(nil)); end

  private

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/column_methods.rb#50
  def valid_column_definition_options; end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/database_statements.rb#6
module ActiveRecord::ConnectionAdapters::PostGIS::DatabaseStatements
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/database_statements.rb#7
  def truncate_tables(*table_names); end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#6
module ActiveRecord::ConnectionAdapters::PostGIS::OID; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/date_time.rb#7
module ActiveRecord::ConnectionAdapters::PostGIS::OID::DateTime
  protected

  # Uses PostGIS instead of PostgreSQLAdapter
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/date_time.rb#11
  def real_type_unless_aliased(real_type); end
end

# OID used to represent geometry/geography database types and attributes.
#
# Accepts `geo_type`, `srid`, `has_z`, `has_m`, and `geographic` as parameters.
# Responsible for parsing sql_types returned from the database and WKT features.
#
# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#11
class ActiveRecord::ConnectionAdapters::PostGIS::OID::Spatial < ::ActiveModel::Type::Value
  # @return [Spatial] a new instance of Spatial
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#12
  def initialize(geo_type: T.unsafe(nil), srid: T.unsafe(nil), has_z: T.unsafe(nil), has_m: T.unsafe(nil), geographic: T.unsafe(nil)); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#87
  def ==(other); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#92
  def eql?(other); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#94
  def hash; end

  # support setting an RGeo object or a WKT string
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#75
  def serialize(value); end

  # @return [Boolean]
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#66
  def spatial?; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#60
  def spatial_factory; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#70
  def type; end

  protected

  # Returns the value of attribute factory_attrs.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#23
  def factory_attrs; end

  # Returns the value of attribute geographic.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#23
  def geographic; end

  private

  # @return [Boolean]
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#112
  def binary_string?(string); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#100
  def cast_value(value); end

  # convert WKT string into RGeo object
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#106
  def parse_wkt(string); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#116
  def wkt_parser(string); end

  class << self
    # sql_type: geometry, geometry(Point), geometry(Point,4326), ...
    #
    # returns [geo_type, srid, has_z, has_m]
    #   geo_type: geography, geometry, point, line_string, polygon, ...
    #   srid:     1234
    #   has_z:    false
    #   has_m:    false
    #
    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/oid/spatial.rb#32
    def parse_sql_type(sql_type); end
  end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/quoting.rb#6
module ActiveRecord::ConnectionAdapters::PostGIS::Quoting
  # NOTE: This method should be private in future rails versions.
  #   Hence we should also make it private then.
  #
  # See https://github.com/rails/rails/blob/v8.1.1/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L190
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/quoting.rb#20
  def lookup_cast_type(sql_type); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/quoting.rb#7
  def type_cast(value); end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/schema_statements.rb#6
module ActiveRecord::ConnectionAdapters::PostGIS::SchemaStatements
  # override
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/schema_statements.rb#45
  def create_table_definition(*args, **kwargs); end

  # override
  # https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L662
  # Create a SpatialColumn instead of a PostgreSQL::Column
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/schema_statements.rb#10
  def new_column_from_field(table_name, field, _definitions); end

  # memoize hash of column infos for tables
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/schema_statements.rb#50
  def spatial_column_info(table_name); end

  # Returns an array of view names defined in the database.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/schema_statements.rb#56
  def views; end
end

# Do spatial sql queries for column info and memoize that info.
#
# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_column_info.rb#7
class ActiveRecord::ConnectionAdapters::PostGIS::SpatialColumnInfo
  # @return [SpatialColumnInfo] a new instance of SpatialColumnInfo
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_column_info.rb#8
  def initialize(adapter, table_name); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_column_info.rb#13
  def all; end

  # do not query the database for non-spatial columns/tables
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_column_info.rb#38
  def get(column_name, type); end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_table_definition.rb#6
class ActiveRecord::ConnectionAdapters::PostGIS::TableDefinition < ::ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition
  include ::ActiveRecord::ConnectionAdapters::PostGIS::ColumnMethods

  # super: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/spatial_table_definition.rb#10
  def new_column_definition(name, type, **options); end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/type.rb#6
module ActiveRecord::ConnectionAdapters::PostGIS::Type
  # Look for :postgis types first, then check for :postgresql
  # types to simulate a kind of Type inheritance.
  #
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/type.rb#9
  def lookup(*args, adapter: T.unsafe(nil), **kwargs); end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/version.rb#6
ActiveRecord::ConnectionAdapters::PostGIS::VERSION = T.let(T.unsafe(nil), String)

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#26
class ActiveRecord::ConnectionAdapters::PostGISAdapter < ::ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
  include ::ActiveRecord::ConnectionAdapters::PostGIS::Quoting
  include ::ActiveRecord::ConnectionAdapters::PostGIS::SchemaStatements
  include ::ActiveRecord::ConnectionAdapters::PostGIS::DatabaseStatements

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#50
  def arel_visitor; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#62
  def default_srid; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#58
  def postgis_lib_version; end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#119
  def quote(value); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#129
  def quote_default_expression(value, column); end

  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#110
  def srs_database_columns; end

  class << self
    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#67
    def initialize_type_map(map = T.unsafe(nil)); end

    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#94
    def native_database_types; end

    # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#54
    def spatial_column_options(key); end
  end
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#27
ActiveRecord::ConnectionAdapters::PostGISAdapter::ADAPTER_NAME = T.let(T.unsafe(nil), String)

# http://postgis.17.x6.nabble.com/Default-SRID-td5001115.html
#
# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#44
ActiveRecord::ConnectionAdapters::PostGISAdapter::DEFAULT_SRID = T.let(T.unsafe(nil), Integer)

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis_adapter.rb#29
ActiveRecord::ConnectionAdapters::PostGISAdapter::SPATIAL_COLUMN_OPTIONS = T.let(T.unsafe(nil), Hash)

module ActiveRecord::ConnectionAdapters::PostgreSQL; end
module ActiveRecord::ConnectionAdapters::PostgreSQL::OID; end

class ActiveRecord::ConnectionAdapters::PostgreSQL::OID::DateTime < ::ActiveRecord::Type::DateTime
  include ::ActiveRecord::ConnectionAdapters::PostGIS::OID::DateTime
end

class ActiveRecord::ConnectionAdapters::PostgreSQL::Table < ::ActiveRecord::ConnectionAdapters::Table
  include ::ActiveRecord::ConnectionAdapters::PostGIS::ColumnMethods
end

module ActiveRecord::Type
  extend ::ActiveRecord::ConnectionAdapters::PostGIS::Type
end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#21
module Arel; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#22
module Arel::Visitors; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#30
class Arel::Visitors::PostGIS < ::Arel::Visitors::PostgreSQL
  include ::RGeo::ActiveRecord::SpatialToSql
  include ::RGeo::ActiveRecord::SpatialToPostGISSql
end

# Different super-class under JRuby JDBC adapter.
#
# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#24
Arel::Visitors::PostGISSuperclass = Arel::Visitors::PostgreSQL

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#3
module RGeo; end

# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#4
module RGeo::ActiveRecord; end

# Extend rgeo-activerecord visitors to use PostGIS specific functionality
#
# source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#7
module RGeo::ActiveRecord::SpatialToPostGISSql
  # source://activerecord-postgis-adapter//lib/active_record/connection_adapters/postgis/arel_tosql.rb#8
  def visit_in_spatial_context(node, collector); end
end

module RGeo::ActiveRecord::SpatialToSql
  include ::RGeo::ActiveRecord::SpatialToPostGISSql
end
