# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `action_push_native` gem.
# Please instead update this file by running `bin/tapioca gem action_push_native`.


# source://action_push_native//lib/action_push_native/engine.rb#3
module ActionPushNative
  class << self
    # source://action_push_native//lib/action_push_native.rb#29
    def config_for(platform, notification); end

    # source://action_push_native//lib/action_push_native.rb#41
    def deprecator; end

    # source://action_push_native//lib/action_push_native/engine.rb#5
    def railtie_helpers_paths; end

    # source://action_push_native//lib/action_push_native/engine.rb#5
    def railtie_namespace; end

    # source://action_push_native//lib/action_push_native/engine.rb#5
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://action_push_native//lib/action_push_native.rb#16
    def service_for(platform, notification); end

    # source://action_push_native//lib/action_push_native/engine.rb#5
    def table_name_prefix; end

    # source://action_push_native//lib/action_push_native/engine.rb#5
    def use_relative_model_naming?; end
  end
end

# source://action_push_native//lib/action_push_native/errors.rb#13
class ActionPushNative::BadDeviceTopicError < ::StandardError; end

# source://action_push_native//lib/action_push_native/errors.rb#7
class ActionPushNative::BadRequestError < ::StandardError; end

# source://action_push_native//lib/action_push_native/configured_notification.rb#2
class ActionPushNative::ConfiguredNotification
  # @return [ConfiguredNotification] a new instance of ConfiguredNotification
  #
  # source://action_push_native//lib/action_push_native/configured_notification.rb#3
  def initialize(notification_class); end

  # source://action_push_native//lib/action_push_native/configured_notification.rb#8
  def new(**attributes); end

  # source://action_push_native//lib/action_push_native/configured_notification.rb#17
  def silent; end

  # source://action_push_native//lib/action_push_native/configured_notification.rb#22
  def with_apple(apple_data); end

  # source://action_push_native//lib/action_push_native/configured_notification.rb#12
  def with_data(data); end

  # source://action_push_native//lib/action_push_native/configured_notification.rb#27
  def with_google(google_data); end

  private

  # Returns the value of attribute notification_class.
  #
  # source://action_push_native//lib/action_push_native/configured_notification.rb#33
  def notification_class; end

  # Returns the value of attribute options.
  #
  # source://action_push_native//lib/action_push_native/configured_notification.rb#33
  def options; end
end

# source://action_push_native//lib/action_push_native/errors.rb#5
class ActionPushNative::ConnectionError < ::StandardError; end

class ActionPushNative::Device < ::ApplicationRecord
  include ::ActionPushNative::Device::GeneratedAttributeMethods
  include ::ActionPushNative::Device::GeneratedAssociationMethods
  include ::ActiveSupport::Rescuable
  extend ::ActiveSupport::Rescuable::ClassMethods

  def autosave_associated_records_for_owner(*args); end
  def push(notification); end
  def rescue_handlers; end
  def rescue_handlers=(_arg0); end
  def rescue_handlers?; end

  class << self
    def apple(*args, **_arg1); end
    def google(*args, **_arg1); end
    def not_apple(*args, **_arg1); end
    def not_google(*args, **_arg1); end
    def platforms; end
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

module ActionPushNative::Device::GeneratedAssociationMethods
  def owner; end
  def owner=(value); end
  def owner_changed?; end
  def owner_previously_changed?; end
  def reload_owner; end
  def reset_owner; end
end

module ActionPushNative::Device::GeneratedAttributeMethods; end

# source://action_push_native//lib/action_push_native/engine.rb#4
class ActionPushNative::Engine < ::Rails::Engine; end

# source://action_push_native//lib/action_push_native/errors.rb#8
class ActionPushNative::ForbiddenError < ::StandardError; end

# source://action_push_native//lib/action_push_native/errors.rb#12
class ActionPushNative::InternalServerError < ::StandardError; end

# source://action_push_native//lib/action_push_native/errors.rb#14
class ActionPushNative::NotFoundError < ::StandardError; end

# = Action Push Native Notification
#
# A notification that can be delivered to devices.
#
# source://action_push_native//lib/action_push_native/notification.rb#7
class ActionPushNative::Notification
  include ::ActiveSupport::Callbacks
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker

  # === Attributes
  #
  #   title - The title
  #   body - The message body
  #   badge - The badge number to display on the app icon
  #   thread_id - The thread ID for grouping notifications
  #   sound - The sound to play when the notification is received
  #   high_priority - Whether to send the notification with high priority (default: true).
  #                   For silent notifications is recommended to set this to false
  #   apple_data - Apple Push Notification Service (APNS) specific data
  #   google_data - Firebase Cloud Messaging (FCM) specific data
  #   data - Custom data to be sent with the notification
  #
  #   Any extra attributes are set inside the `context` hash.
  #
  # @return [Notification] a new instance of Notification
  #
  # source://action_push_native//lib/action_push_native/notification.rb#47
  def initialize(title: T.unsafe(nil), body: T.unsafe(nil), badge: T.unsafe(nil), thread_id: T.unsafe(nil), sound: T.unsafe(nil), high_priority: T.unsafe(nil), apple_data: T.unsafe(nil), google_data: T.unsafe(nil), data: T.unsafe(nil), **context); end

  # source://action_push_native//lib/action_push_native/notification.rb#8
  def __callbacks; end

  # source://action_push_native//lib/action_push_native/notification.rb#14
  def _delivery_callbacks; end

  # source://action_push_native//lib/action_push_native/notification.rb#14
  def _run_delivery_callbacks(&block); end

  # Returns the value of attribute apple_data.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def apple_data; end

  # Sets the attribute apple_data
  #
  # @param value the value to set the attribute apple_data to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def apple_data=(_arg0); end

  # source://action_push_native//lib/action_push_native/notification.rb#18
  def application; end

  # source://action_push_native//lib/action_push_native/notification.rb#18
  def application=(_arg0); end

  # source://action_push_native//lib/action_push_native/notification.rb#18
  def application?; end

  # source://action_push_native//lib/action_push_native/notification.rb#72
  def as_json; end

  # Returns the value of attribute badge.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def badge; end

  # Sets the attribute badge
  #
  # @param value the value to set the attribute badge to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def badge=(_arg0); end

  # Returns the value of attribute body.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def body; end

  # Sets the attribute body
  #
  # @param value the value to set the attribute body to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def body=(_arg0); end

  # Returns the value of attribute context.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#11
  def context; end

  # Sets the attribute context
  #
  # @param value the value to set the attribute context to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#11
  def context=(_arg0); end

  # Returns the value of attribute data.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def data; end

  # Sets the attribute data
  #
  # @param value the value to set the attribute data to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def data=(_arg0); end

  # source://action_push_native//lib/action_push_native/notification.rb#66
  def deliver_later_to(devices); end

  # source://action_push_native//lib/action_push_native/notification.rb#60
  def deliver_to(device); end

  # source://action_push_native//lib/action_push_native/notification.rb#17
  def enabled; end

  # source://action_push_native//lib/action_push_native/notification.rb#17
  def enabled=(_arg0); end

  # source://action_push_native//lib/action_push_native/notification.rb#17
  def enabled?; end

  # Returns the value of attribute google_data.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def google_data; end

  # Sets the attribute google_data
  #
  # @param value the value to set the attribute google_data to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def google_data=(_arg0); end

  # Returns the value of attribute high_priority.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def high_priority; end

  # Sets the attribute high_priority
  #
  # @param value the value to set the attribute high_priority to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def high_priority=(_arg0); end

  # source://action_push_native//lib/action_push_native/notification.rb#16
  def queue_name; end

  # source://action_push_native//lib/action_push_native/notification.rb#16
  def queue_name=(_arg0); end

  # source://action_push_native//lib/action_push_native/notification.rb#16
  def queue_name?; end

  # Returns the value of attribute sound.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def sound; end

  # Sets the attribute sound
  #
  # @param value the value to set the attribute sound to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def sound=(_arg0); end

  # Returns the value of attribute thread_id.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def thread_id; end

  # Sets the attribute thread_id
  #
  # @param value the value to set the attribute thread_id to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def thread_id=(_arg0); end

  # Returns the value of attribute title.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def title; end

  # Sets the attribute title
  #
  # @param value the value to set the attribute title to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#10
  def title=(_arg0); end

  # Returns the value of attribute token.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#12
  def token; end

  # Sets the attribute token
  #
  # @param value the value to set the attribute token to.
  #
  # source://action_push_native//lib/action_push_native/notification.rb#12
  def token=(_arg0); end

  class << self
    # source://action_push_native//lib/action_push_native/notification.rb#8
    def __callbacks; end

    # source://action_push_native//lib/action_push_native/notification.rb#8
    def __callbacks=(value); end

    # source://action_push_native//lib/action_push_native/notification.rb#14
    def _delivery_callbacks; end

    # source://action_push_native//lib/action_push_native/notification.rb#14
    def _delivery_callbacks=(value); end

    # source://action_push_native//lib/action_push_native/notification.rb#14
    def after_delivery(*args, **options, &block); end

    # source://action_push_native//lib/action_push_native/notification.rb#18
    def application; end

    # source://action_push_native//lib/action_push_native/notification.rb#18
    def application=(value); end

    # source://action_push_native//lib/action_push_native/notification.rb#18
    def application?; end

    # source://action_push_native//lib/action_push_native/notification.rb#14
    def around_delivery(*args, **options, &block); end

    # source://action_push_native//lib/action_push_native/notification.rb#14
    def before_delivery(*args, **options, &block); end

    # source://action_push_native//lib/action_push_native/notification.rb#17
    def enabled; end

    # source://action_push_native//lib/action_push_native/notification.rb#17
    def enabled=(value); end

    # source://action_push_native//lib/action_push_native/notification.rb#17
    def enabled?; end

    # source://action_push_native//lib/action_push_native/notification.rb#21
    def queue_as(name); end

    # source://action_push_native//lib/action_push_native/notification.rb#16
    def queue_name; end

    # source://action_push_native//lib/action_push_native/notification.rb#16
    def queue_name=(value); end

    # source://action_push_native//lib/action_push_native/notification.rb#16
    def queue_name?; end

    # source://action_push_native//lib/action_push_native/notification.rb#25
    def silent(*_arg0, **_arg1, &_arg2); end

    # source://action_push_native//lib/action_push_native/notification.rb#25
    def with_apple(*_arg0, **_arg1, &_arg2); end

    # source://action_push_native//lib/action_push_native/notification.rb#25
    def with_data(*_arg0, **_arg1, &_arg2); end

    # source://action_push_native//lib/action_push_native/notification.rb#25
    def with_google(*_arg0, **_arg1, &_arg2); end

    private

    # source://action_push_native//lib/action_push_native/notification.rb#8
    def __class_attr___callbacks; end

    # source://action_push_native//lib/action_push_native/notification.rb#8
    def __class_attr___callbacks=(new_value); end

    # source://action_push_native//lib/action_push_native/notification.rb#18
    def __class_attr_application; end

    # source://action_push_native//lib/action_push_native/notification.rb#18
    def __class_attr_application=(new_value); end

    # source://action_push_native//lib/action_push_native/notification.rb#17
    def __class_attr_enabled; end

    # source://action_push_native//lib/action_push_native/notification.rb#17
    def __class_attr_enabled=(new_value); end

    # source://action_push_native//lib/action_push_native/notification.rb#16
    def __class_attr_queue_name; end

    # source://action_push_native//lib/action_push_native/notification.rb#16
    def __class_attr_queue_name=(new_value); end

    # source://action_push_native//lib/action_push_native/notification.rb#28
    def configured_notification; end
  end
end

class ActionPushNative::NotificationJob < ::ActiveJob::Base
  def perform(notification_class, notification_attributes, device); end
  def report_job_retries; end
  def report_job_retries=(_arg0); end
  def report_job_retries?; end

  class << self
    def exponential_backoff_delay(executions); end
    def report_job_retries; end
    def report_job_retries=(value); end
    def report_job_retries?; end
    def retry_options; end

    private

    def __class_attr_log_arguments; end
    def __class_attr_log_arguments=(new_value); end
    def __class_attr_report_job_retries; end
    def __class_attr_report_job_retries=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

# source://action_push_native//lib/action_push_native/errors.rb#9
class ActionPushNative::PayloadTooLargeError < ::StandardError; end

# source://action_push_native//lib/action_push_native/service/apns.rb#4
module ActionPushNative::Service; end

# source://action_push_native//lib/action_push_native/service/apns.rb#5
class ActionPushNative::Service::Apns
  include ::ActionPushNative::Service::NetworkErrorHandling

  # @return [Apns] a new instance of Apns
  #
  # source://action_push_native//lib/action_push_native/service/apns.rb#11
  def initialize(config); end

  # source://action_push_native//lib/action_push_native/service/apns.rb#9
  def httpx_sessions; end

  # source://action_push_native//lib/action_push_native/service/apns.rb#9
  def httpx_sessions=(val); end

  # source://action_push_native//lib/action_push_native/service/apns.rb#15
  def push(notification); end

  private

  # Returns the value of attribute config.
  #
  # source://action_push_native//lib/action_push_native/service/apns.rb#25
  def config; end

  # source://action_push_native//lib/action_push_native/service/apns.rb#75
  def handle_apns_error(response); end

  # source://action_push_native//lib/action_push_native/service/apns.rb#67
  def handle_error(response); end

  # source://action_push_native//lib/action_push_native/service/apns.rb#30
  def headers_from(notification); end

  # source://action_push_native//lib/action_push_native/service/apns.rb#62
  def httpx_session; end

  # source://action_push_native//lib/action_push_native/service/apns.rb#42
  def payload_from(notification); end

  class << self
    # source://action_push_native//lib/action_push_native/service/apns.rb#9
    def httpx_sessions; end

    # source://action_push_native//lib/action_push_native/service/apns.rb#9
    def httpx_sessions=(val); end
  end
end

# Converts the legacy `apple_data` format from the Apnotic gem
# to the new format expected by the APNs API.
#
# Temporary compatibility layer: It will be removed in the next release.
#
# source://action_push_native//lib/action_push_native/service/apns/apnotic_legacy_converter.rb#7
class ActionPushNative::Service::Apns::ApnoticLegacyConverter
  class << self
    # source://action_push_native//lib/action_push_native/service/apns/apnotic_legacy_converter.rb#15
    def convert(apple_data); end
  end
end

# source://action_push_native//lib/action_push_native/service/apns/apnotic_legacy_converter.rb#13
ActionPushNative::Service::Apns::ApnoticLegacyConverter::APNS_HEADERS = T.let(T.unsafe(nil), Array)

# source://action_push_native//lib/action_push_native/service/apns/apnotic_legacy_converter.rb#8
ActionPushNative::Service::Apns::ApnoticLegacyConverter::APS_FIELDS = T.let(T.unsafe(nil), Array)

# source://action_push_native//lib/action_push_native/service/apns.rb#28
ActionPushNative::Service::Apns::HEADERS = T.let(T.unsafe(nil), Array)

# source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#3
class ActionPushNative::Service::Apns::HttpxSession
  # @return [HttpxSession] a new instance of HttpxSession
  #
  # source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#9
  def initialize(config); end

  # source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#19
  def post(*uri, **options); end

  private

  # Returns the value of attribute session.
  #
  # source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#25
  def session; end

  # Returns the value of attribute token_provider.
  #
  # source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#25
  def token_provider; end
end

# source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#4
ActionPushNative::Service::Apns::HttpxSession::DEFAULT_POOL_SIZE = T.let(T.unsafe(nil), Integer)

# source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#5
ActionPushNative::Service::Apns::HttpxSession::DEFAULT_REQUEST_TIMEOUT = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#6
ActionPushNative::Service::Apns::HttpxSession::DEVELOPMENT_SERVER_URL = T.let(T.unsafe(nil), String)

# source://action_push_native//lib/action_push_native/service/apns/httpx_session.rb#7
ActionPushNative::Service::Apns::HttpxSession::PRODUCTION_SERVER_URL = T.let(T.unsafe(nil), String)

# source://action_push_native//lib/action_push_native/service/apns.rb#27
ActionPushNative::Service::Apns::PRIORITIES = T.let(T.unsafe(nil), Hash)

# source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#3
class ActionPushNative::Service::Apns::TokenProvider
  # @return [TokenProvider] a new instance of TokenProvider
  #
  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#6
  def initialize(config); end

  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#11
  def fresh_access_token; end

  private

  # Returns the value of attribute config.
  #
  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#17
  def config; end

  # Returns the value of attribute expires_at.
  #
  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#17
  def expires_at; end

  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#27
  def generate; end

  # See https://developer.apple.com/documentation/usernotifications/establishing-a-token-based-connection-to-apns#Refresh-your-token-regularly
  #
  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#20
  def regenerate_if_expired; end

  # Returns the value of attribute token.
  #
  # source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#17
  def token; end
end

# source://action_push_native//lib/action_push_native/service/apns/token_provider.rb#4
ActionPushNative::Service::Apns::TokenProvider::EXPIRED = T.let(T.unsafe(nil), Integer)

# source://action_push_native//lib/action_push_native/service/fcm.rb#5
class ActionPushNative::Service::Fcm
  include ::ActionPushNative::Service::NetworkErrorHandling

  # @return [Fcm] a new instance of Fcm
  #
  # source://action_push_native//lib/action_push_native/service/fcm.rb#11
  def initialize(config); end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#9
  def httpx_sessions; end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#9
  def httpx_sessions=(val); end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#15
  def push(notification); end

  private

  # Returns the value of attribute config.
  #
  # source://action_push_native//lib/action_push_native/service/fcm.rb#21
  def config; end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#47
  def deep_compact(payload); end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#65
  def handle_error(response); end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#73
  def handle_fcm_error(response); end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#23
  def httpx_session; end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#28
  def payload_from(notification); end

  # source://action_push_native//lib/action_push_native/service/fcm.rb#61
  def stringify(hash); end

  # FCM requires data values to be strings.
  #
  # source://action_push_native//lib/action_push_native/service/fcm.rb#55
  def stringify_data(google_data); end

  class << self
    # source://action_push_native//lib/action_push_native/service/fcm.rb#9
    def httpx_sessions; end

    # source://action_push_native//lib/action_push_native/service/fcm.rb#9
    def httpx_sessions=(val); end
  end
end

# source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#3
class ActionPushNative::Service::Fcm::HttpxSession
  # @return [HttpxSession] a new instance of HttpxSession
  #
  # source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#9
  def initialize(config); end

  # source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#19
  def post(*uri, **options); end

  private

  # Returns the value of attribute session.
  #
  # source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#26
  def session; end

  # Returns the value of attribute token_provider.
  #
  # source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#26
  def token_provider; end
end

# source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#7
ActionPushNative::Service::Fcm::HttpxSession::DEFAULT_POOL_SIZE = T.let(T.unsafe(nil), Integer)

# FCM suggests at least a 10s timeout for requests, we set 15 to add some buffer.
# https://firebase.google.com/docs/cloud-messaging/scale-fcm#timeouts
#
# source://action_push_native//lib/action_push_native/service/fcm/httpx_session.rb#6
ActionPushNative::Service::Fcm::HttpxSession::DEFAULT_REQUEST_TIMEOUT = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#3
class ActionPushNative::Service::Fcm::TokenProvider
  # @return [TokenProvider] a new instance of TokenProvider
  #
  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#6
  def initialize(config); end

  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#11
  def fresh_access_token; end

  private

  # Returns the value of attribute config.
  #
  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#17
  def config; end

  # Returns the value of attribute expires_at.
  #
  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#17
  def expires_at; end

  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#25
  def regenerate; end

  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#19
  def regenerate_if_expired; end

  # Returns the value of attribute token.
  #
  # source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#17
  def token; end
end

# source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#4
ActionPushNative::Service::Fcm::TokenProvider::EXPIRED = T.let(T.unsafe(nil), Integer)

# source://action_push_native//lib/action_push_native/service/fcm/token_provider.rb#23
ActionPushNative::Service::Fcm::TokenProvider::REFRESH_BUFFER = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://action_push_native//lib/action_push_native/service/network_error_handling.rb#1
module ActionPushNative::Service::NetworkErrorHandling
  private

  # source://action_push_native//lib/action_push_native/service/network_error_handling.rb#4
  def handle_network_error(error); end
end

# source://action_push_native//lib/action_push_native/errors.rb#11
class ActionPushNative::ServiceUnavailableError < ::StandardError; end

# source://action_push_native//lib/action_push_native/errors.rb#4
class ActionPushNative::TimeoutError < ::StandardError; end

# source://action_push_native//lib/action_push_native/errors.rb#16
class ActionPushNative::TokenError < ::StandardError; end

# source://action_push_native//lib/action_push_native/errors.rb#10
class ActionPushNative::TooManyRequestsError < ::StandardError; end

# source://action_push_native//lib/action_push_native/version.rb#2
ActionPushNative::VERSION = T.let(T.unsafe(nil), String)
