# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `apple_id` gem.
# Please instead update this file by running `bin/tapioca gem apple_id`.


# source://apple_id//lib/apple_id.rb#3
module AppleID
  class << self
    # source://apple_id//lib/apple_id.rb#40
    def debug(&block); end

    # source://apple_id//lib/apple_id.rb#34
    def debug!; end

    # source://apple_id//lib/apple_id.rb#28
    def debugging=(boolean); end

    # @return [Boolean]
    #
    # source://apple_id//lib/apple_id.rb#25
    def debugging?; end

    # source://apple_id//lib/apple_id.rb#13
    def logger; end

    # source://apple_id//lib/apple_id.rb#16
    def logger=(logger); end
  end
end

# source://apple_id//lib/apple_id/api/user_migration.rb#2
module AppleID::API; end

# source://apple_id//lib/apple_id/api/user_migration.rb#3
module AppleID::API::UserMigration
  # source://apple_id//lib/apple_id/api/user_migration.rb#4
  def transfer_from!(transfer_sub:); end

  # source://apple_id//lib/apple_id/api/user_migration.rb#15
  def transfer_to!(sub:, target:); end

  private

  # source://apple_id//lib/apple_id/api/user_migration.rb#29
  def user_migration_endpoint; end
end

# source://apple_id//lib/apple_id/access_token.rb#2
class AppleID::AccessToken < ::OpenIDConnect::AccessToken
  include ::AppleID::API::UserMigration

  # @return [AccessToken] a new instance of AccessToken
  #
  # source://apple_id//lib/apple_id/access_token.rb#6
  def initialize(access_token, attributes = T.unsafe(nil)); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def access_token; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def access_token=(_arg0); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def client; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def client=(_arg0); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def expires_in; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def expires_in=(_arg0); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def id_token; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def id_token=(_arg0); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def refresh_token; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def refresh_token=(_arg0); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def scope; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def scope=(_arg0); end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def token_type; end

  # source://apple_id//lib/apple_id/access_token.rb#2
  def token_type=(_arg0); end
end

# source://apple_id//lib/apple_id/client.rb#2
class AppleID::Client < ::OpenIDConnect::Client
  # @return [Client] a new instance of Client
  #
  # source://apple_id//lib/apple_id/client.rb#7
  def initialize(attributes); end

  # source://apple_id//lib/apple_id/client.rb#16
  def access_token!(options = T.unsafe(nil)); end

  # source://apple_id//lib/apple_id/client.rb#2
  def authorization_endpoint; end

  # source://apple_id//lib/apple_id/client.rb#2
  def authorization_endpoint=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def certificate; end

  # source://apple_id//lib/apple_id/client.rb#2
  def certificate=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def expires_in; end

  # source://apple_id//lib/apple_id/client.rb#2
  def expires_in=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def host; end

  # source://apple_id//lib/apple_id/client.rb#2
  def host=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def identifier; end

  # source://apple_id//lib/apple_id/client.rb#2
  def identifier=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#5
  def key_id; end

  # source://apple_id//lib/apple_id/client.rb#5
  def key_id=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def port; end

  # source://apple_id//lib/apple_id/client.rb#2
  def port=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def private_key; end

  # source://apple_id//lib/apple_id/client.rb#2
  def private_key=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def redirect_uri; end

  # source://apple_id//lib/apple_id/client.rb#2
  def redirect_uri=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def revocation_endpoint; end

  # source://apple_id//lib/apple_id/client.rb#2
  def revocation_endpoint=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#21
  def revoke!(options = T.unsafe(nil)); end

  # source://apple_id//lib/apple_id/client.rb#2
  def scheme; end

  # source://apple_id//lib/apple_id/client.rb#2
  def scheme=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def secret; end

  # source://apple_id//lib/apple_id/client.rb#2
  def secret=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#5
  def team_id; end

  # source://apple_id//lib/apple_id/client.rb#5
  def team_id=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def token_endpoint; end

  # source://apple_id//lib/apple_id/client.rb#2
  def token_endpoint=(_arg0); end

  # source://apple_id//lib/apple_id/client.rb#2
  def userinfo_endpoint; end

  # source://apple_id//lib/apple_id/client.rb#2
  def userinfo_endpoint=(_arg0); end

  private

  # source://apple_id//lib/apple_id/client.rb#28
  def client_secret_jwt; end

  # source://apple_id//lib/apple_id/client.rb#52
  def handle_error_response(response); end

  # source://apple_id//lib/apple_id/client.rb#47
  def handle_success_response(response); end

  # source://apple_id//lib/apple_id/client.rb#40
  def setup_required_scope(scopes); end
end

# source://apple_id//lib/apple_id/client.rb#3
class AppleID::Client::Error < ::Rack::OAuth2::Client::Error; end

# source://apple_id//lib/apple_id.rb#11
class AppleID::Error < ::StandardError; end

# source://apple_id//lib/apple_id/event_token.rb#2
class AppleID::EventToken < ::OpenIDConnect::ConnectObject
  # @return [EventToken] a new instance of EventToken
  #
  # source://apple_id//lib/apple_id/event_token.rb#11
  def initialize(attributes = T.unsafe(nil)); end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def account_deleted?(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def aud; end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def aud=(_arg0); end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def consent_revoked?(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def email_disabled?(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def email_enabled?(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#7
  def event; end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def event_time(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def events; end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def events=(_arg0); end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def exp; end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def exp=(_arg0); end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def iat; end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def iat=(_arg0); end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def iss; end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def iss=(_arg0); end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def jti; end

  # source://apple_id//lib/apple_id/event_token.rb#5
  def jti=(_arg0); end

  # source://apple_id//lib/apple_id/event_token.rb#6
  def original_jwt; end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def sub(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#9
  def type(*_arg0, **_arg1, &_arg2); end

  # source://apple_id//lib/apple_id/event_token.rb#16
  def verify!(verify_signature: T.unsafe(nil), client: T.unsafe(nil)); end

  private

  # source://apple_id//lib/apple_id/event_token.rb#36
  def verify_claims!(client); end

  # source://apple_id//lib/apple_id/event_token.rb#30
  def verify_signature!; end

  class << self
    # source://apple_id//lib/apple_id/event_token.rb#23
    def decode(jwt_string); end

    private

    # source://apple_id//lib/apple_id/event_token.rb#2
    def __class_attr__validators; end

    # source://apple_id//lib/apple_id/event_token.rb#2
    def __class_attr__validators=(new_value); end
  end
end

# source://apple_id//lib/apple_id/event_token/event.rb#2
class AppleID::EventToken::Event < ::OpenIDConnect::ConnectObject
  # source://apple_id//lib/apple_id/event_token/event.rb#28
  def account_delete?; end

  # source://apple_id//lib/apple_id/event_token/event.rb#25
  def account_deleted?; end

  # source://apple_id//lib/apple_id/event_token/event.rb#21
  def consent_revoked?; end

  # source://apple_id//lib/apple_id/event_token/event.rb#4
  def email; end

  # source://apple_id//lib/apple_id/event_token/event.rb#4
  def email=(_arg0); end

  # source://apple_id//lib/apple_id/event_token/event.rb#17
  def email_disabled?; end

  # source://apple_id//lib/apple_id/event_token/event.rb#13
  def email_enabled?; end

  # source://apple_id//lib/apple_id/event_token/event.rb#3
  def event_time; end

  # source://apple_id//lib/apple_id/event_token/event.rb#3
  def event_time=(_arg0); end

  # source://apple_id//lib/apple_id/event_token/event.rb#4
  def is_private_email; end

  # source://apple_id//lib/apple_id/event_token/event.rb#4
  def is_private_email=(_arg0); end

  # source://apple_id//lib/apple_id/event_token/event.rb#30
  def is_private_email?; end

  # source://apple_id//lib/apple_id/event_token/event.rb#3
  def sub; end

  # source://apple_id//lib/apple_id/event_token/event.rb#3
  def sub=(_arg0); end

  # source://apple_id//lib/apple_id/event_token/event.rb#3
  def type; end

  # source://apple_id//lib/apple_id/event_token/event.rb#3
  def type=(_arg0); end

  class << self
    # source://apple_id//lib/apple_id/event_token/event.rb#39
    def decode(json_string); end

    private

    # source://apple_id//lib/apple_id/event_token/event.rb#2
    def __class_attr__validators; end

    # source://apple_id//lib/apple_id/event_token/event.rb#2
    def __class_attr__validators=(new_value); end
  end
end

# source://apple_id//lib/apple_id/event_token/event.rb#6
module AppleID::EventToken::Event::Type; end

# source://apple_id//lib/apple_id/event_token/event.rb#10
AppleID::EventToken::Event::Type::ACCOUNT_DELETED = T.let(T.unsafe(nil), String)

# source://apple_id//lib/apple_id/event_token/event.rb#9
AppleID::EventToken::Event::Type::CONSENT_REVOKED = T.let(T.unsafe(nil), String)

# source://apple_id//lib/apple_id/event_token/event.rb#8
AppleID::EventToken::Event::Type::EMAIL_DISABLED = T.let(T.unsafe(nil), String)

# source://apple_id//lib/apple_id/event_token/event.rb#7
AppleID::EventToken::Event::Type::EMAIL_ENABLED = T.let(T.unsafe(nil), String)

# source://apple_id//lib/apple_id/event_token.rb#3
class AppleID::EventToken::VerificationFailed < ::AppleID::Error; end

# source://apple_id//lib/apple_id.rb#4
AppleID::ISSUER = T.let(T.unsafe(nil), String)

# source://apple_id//lib/apple_id/id_token.rb#2
class AppleID::IdToken < ::OpenIDConnect::ResponseObject::IdToken
  # @return [IdToken] a new instance of IdToken
  #
  # source://apple_id//lib/apple_id/id_token.rb#21
  def initialize(attributes = T.unsafe(nil)); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def acr; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def acr=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def amr; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def amr=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def at_hash; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def at_hash=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def aud; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def aud=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def auth_time; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def auth_time=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def azp; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def azp=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def c_hash; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def c_hash=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def email; end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def email=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def email_verified; end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def email_verified=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#10
  def email_verified?; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def exp; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def exp=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def iat; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def iat=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def is_private_email; end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def is_private_email=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#10
  def is_private_email?; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def iss; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def iss=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def jti; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def jti=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def nonce; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def nonce=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def nonce_supported; end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def nonce_supported=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#10
  def nonce_supported?; end

  # source://apple_id//lib/apple_id/id_token.rb#7
  def original_jwt; end

  # Returns the value of attribute original_jwt_string.
  #
  # source://apple_id//lib/apple_id/id_token.rb#6
  def original_jwt_string; end

  # Sets the attribute original_jwt_string
  #
  # @param value the value to set the attribute original_jwt_string to.
  #
  # source://apple_id//lib/apple_id/id_token.rb#6
  def original_jwt_string=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def real_user_status; end

  # source://apple_id//lib/apple_id/id_token.rb#5
  def real_user_status=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def s_hash; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def s_hash=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def sid; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def sid=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def sub; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def sub=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def sub_jwk; end

  # source://apple_id//lib/apple_id/id_token.rb#2
  def sub_jwk=(_arg0); end

  # source://apple_id//lib/apple_id/id_token.rb#28
  def verify!(verify_signature: T.unsafe(nil), client: T.unsafe(nil), nonce: T.unsafe(nil), state: T.unsafe(nil), access_token: T.unsafe(nil), code: T.unsafe(nil)); end

  private

  # source://apple_id//lib/apple_id/id_token.rb#50
  def verify_claims!(client, nonce, state, access_token, code); end

  # source://apple_id//lib/apple_id/id_token.rb#44
  def verify_signature!; end

  class << self
    # source://apple_id//lib/apple_id/id_token.rb#35
    def decode(jwt_string); end

    private

    # source://apple_id//lib/apple_id/id_token.rb#2
    def __class_attr__validators; end

    # source://apple_id//lib/apple_id/id_token.rb#2
    def __class_attr__validators=(new_value); end
  end
end

# source://apple_id//lib/apple_id/id_token/real_user_status.rb#2
class AppleID::IdToken::RealUserStatus
  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#13
  def initialize(value); end

  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#18
  def likely_real?; end

  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#23
  def status; end

  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#18
  def unknown?; end

  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#18
  def unsupported?; end

  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#5
  def value; end

  # source://apple_id//lib/apple_id/id_token/real_user_status.rb#5
  def value=(_arg0); end
end

# source://apple_id//lib/apple_id/id_token/real_user_status.rb#7
AppleID::IdToken::RealUserStatus::STATUSES = T.let(T.unsafe(nil), Array)

# source://apple_id//lib/apple_id/id_token/real_user_status.rb#3
class AppleID::IdToken::RealUserStatus::UndefinedStatus < ::StandardError; end

# source://apple_id//lib/apple_id/id_token.rb#3
class AppleID::IdToken::VerificationFailed < ::AppleID::Error; end

# source://apple_id//lib/apple_id/jwks.rb#2
class AppleID::JWKS < ::JSON::JWK::Set
  class << self
    # source://apple_id//lib/apple_id/jwks.rb#6
    def cache; end

    # source://apple_id//lib/apple_id/jwks.rb#3
    def cache=(cache); end

    # source://apple_id//lib/apple_id/jwks.rb#10
    def fetch(kid, options = T.unsafe(nil)); end
  end
end

# source://apple_id//lib/apple_id.rb#5
AppleID::JWKS_URI = T.let(T.unsafe(nil), String)

# source://apple_id//lib/apple_id.rb#7
AppleID::VERSION = T.let(T.unsafe(nil), String)
