# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dig_bang` gem.
# Please instead update this file by running `bin/tapioca gem dig_bang`.


# source://dig_bang//lib/dig_bang.rb#14
class Array
  include ::Enumerable

  # source://dig_bang//lib/dig_bang.rb#15
  def dig!(*keys); end
end

# source://dig_bang//lib/dig_bang.rb#2
module DigBang
  class << self
    # source://dig_bang//lib/dig_bang.rb#3
    def fetch_all(fetchable, keys); end
  end
end

# source://dig_bang//lib/dig_bang.rb#8
class Hash
  include ::Enumerable

  # source://dig_bang//lib/dig_bang.rb#9
  def dig!(*keys); end
end
