# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `lexxy` gem.
# Please instead update this file by running `bin/tapioca gem lexxy`.


# source://lexxy//lib/action_text/attachables/remote_video.rb#1
module ActionText; end

# source://lexxy//lib/action_text/attachables/remote_video.rb#2
module ActionText::Attachables; end

# source://lexxy//lib/action_text/attachables/remote_video.rb#3
class ActionText::Attachables::RemoteVideo
  extend ::ActiveModel::Naming

  # @return [RemoteVideo] a new instance of RemoteVideo
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#29
  def initialize(attributes = T.unsafe(nil)); end

  # source://lexxy//lib/action_text/attachables/remote_video.rb#37
  def attachable_plain_text_representation(caption); end

  # Returns the value of attribute content_type.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def content_type; end

  # Returns the value of attribute filename.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def filename; end

  # Returns the value of attribute height.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def height; end

  # source://lexxy//lib/action_text/attachables/remote_video.rb#4
  def model_name(&_arg0); end

  # source://lexxy//lib/action_text/attachables/remote_video.rb#41
  def to_partial_path; end

  # Returns the value of attribute url.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def url; end

  # Returns the value of attribute width.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def width; end

  class << self
    # source://lexxy//lib/action_text/attachables/remote_video.rb#7
    def from_node(node); end

    private

    # source://lexxy//lib/action_text/attachables/remote_video.rb#18
    def attributes_from_node(node); end

    # @return [Boolean]
    #
    # source://lexxy//lib/action_text/attachables/remote_video.rb#14
    def content_type_is_video?(content_type); end
  end
end

# source://lexxy//lib/active_storage/blob_with_preview_url.rb#1
module ActiveStorage; end

# source://lexxy//lib/active_storage/blob_with_preview_url.rb#2
module ActiveStorage::BlobWithPreviewUrl
  # source://lexxy//lib/active_storage/blob_with_preview_url.rb#5
  def as_json(options = T.unsafe(nil)); end
end

# source://lexxy//lib/active_storage/blob_with_preview_url.rb#3
ActiveStorage::BlobWithPreviewUrl::PREVIEW_SIZE = T.let(T.unsafe(nil), Array)

# source://lexxy//lib/lexxy/version.rb#1
module Lexxy
  class << self
    # source://lexxy//lib/lexxy.rb#10
    def override_action_text_defaults; end

    # source://lexxy//lib/lexxy/engine.rb#7
    def railtie_helpers_paths; end

    # source://lexxy//lib/lexxy/engine.rb#7
    def railtie_namespace; end

    # source://lexxy//lib/lexxy/engine.rb#7
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # Check for ActionText::Editor with block-children support (rails/rails#56926)
    #
    # @return [Boolean]
    #
    # source://lexxy//lib/lexxy.rb#6
    def supports_editor_adapter?; end

    # source://lexxy//lib/lexxy/engine.rb#7
    def table_name_prefix; end

    # source://lexxy//lib/lexxy/engine.rb#7
    def use_relative_model_naming?; end
  end
end

# source://lexxy//lib/lexxy/action_text_tag.rb#2
module Lexxy::ActionTextTag
  # source://lexxy//lib/lexxy/action_text_tag.rb#3
  def initialize(object_name, method_name, template_object, options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/action_text_tag.rb#9
  def lexxy_render; end
end

# source://lexxy//lib/lexxy/attachable.rb#4
module Lexxy::Attachable
  # source://lexxy//lib/lexxy/attachable.rb#5
  def from_node(node); end
end

# source://lexxy//lib/lexxy/engine.rb#6
class Lexxy::Engine < ::Rails::Engine; end

# source://lexxy//lib/lexxy/form_builder.rb#2
module Lexxy::FormBuilder
  # source://lexxy//lib/lexxy/form_builder.rb#7
  def lexxy_rich_text_area(method, options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/form_builder.rb#3
  def lexxy_rich_textarea(method, options = T.unsafe(nil), &block); end
end

# source://lexxy//lib/lexxy/form_helper.rb#2
module Lexxy::FormHelper
  # source://lexxy//lib/lexxy/form_helper.rb#7
  def lexxy_rich_text_area(object_name, method, options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/form_helper.rb#3
  def lexxy_rich_textarea(object_name, method, options = T.unsafe(nil), &block); end
end

# source://lexxy//lib/lexxy/rich_text_area_tag.rb#2
module Lexxy::TagHelper
  # source://lexxy//lib/lexxy/rich_text_area_tag.rb#21
  def lexxy_rich_text_area_tag(name, value = T.unsafe(nil), options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/rich_text_area_tag.rb#3
  def lexxy_rich_textarea_tag(name, value = T.unsafe(nil), options = T.unsafe(nil), &block); end

  private

  # Temporary: we need to *adaptarize* action text
  #
  # source://lexxy//lib/lexxy/rich_text_area_tag.rb#25
  def render_custom_attachments_in(value); end
end

# source://lexxy//lib/lexxy/version.rb#2
Lexxy::VERSION = T.let(T.unsafe(nil), String)
