# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prosopite` gem.
# Please instead update this file by running `bin/tapioca gem prosopite`.


# source://prosopite//lib/prosopite.rb#2
module Prosopite
  class << self
    # source://prosopite//lib/prosopite.rb#23
    def allow_list=(value); end

    # Returns the value of attribute allow_stack_paths.
    #
    # source://prosopite//lib/prosopite.rb#19
    def allow_stack_paths; end

    # Sets the attribute allow_stack_paths
    #
    # @param value the value to set the attribute allow_stack_paths to.
    #
    # source://prosopite//lib/prosopite.rb#19
    def allow_stack_paths=(_arg0); end

    # source://prosopite//lib/prosopite.rb#29
    def backtrace_cleaner; end

    # Sets the attribute backtrace_cleaner
    #
    # @param value the value to set the attribute backtrace_cleaner to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def backtrace_cleaner=(_arg0); end

    # source://prosopite//lib/prosopite.rb#132
    def create_notifications; end

    # Sets the attribute custom_logger
    #
    # @param value the value to set the attribute custom_logger to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def custom_logger=(_arg0); end

    # @return [Boolean]
    #
    # source://prosopite//lib/prosopite.rb#39
    def disabled?; end

    # Sets the attribute enabled
    #
    # @param value the value to set the attribute enabled to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def enabled=(_arg0); end

    # @return [Boolean]
    #
    # source://prosopite//lib/prosopite.rb#33
    def enabled?; end

    # source://prosopite//lib/prosopite.rb#162
    def fingerprint(query); end

    # source://prosopite//lib/prosopite.rb#103
    def finish; end

    # Sets the attribute ignore_pauses
    #
    # @param value the value to set the attribute ignore_pauses to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def ignore_pauses=(_arg0); end

    # Returns the value of attribute ignore_queries.
    #
    # source://prosopite//lib/prosopite.rb#19
    def ignore_queries; end

    # Sets the attribute ignore_queries
    #
    # @param value the value to set the attribute ignore_queries to.
    #
    # source://prosopite//lib/prosopite.rb#19
    def ignore_queries=(_arg0); end

    # @return [Boolean]
    #
    # source://prosopite//lib/prosopite.rb#266
    def ignore_query?(sql); end

    # @return [Boolean]
    #
    # source://prosopite//lib/prosopite.rb#124
    def local_raise?; end

    # Returns the value of attribute min_n_queries.
    #
    # source://prosopite//lib/prosopite.rb#19
    def min_n_queries; end

    # Sets the attribute min_n_queries
    #
    # @param value the value to set the attribute min_n_queries to.
    #
    # source://prosopite//lib/prosopite.rb#19
    def min_n_queries=(_arg0); end

    # Many thanks to https://github.com/genkami/fluent-plugin-query-fingerprint/
    #
    # source://prosopite//lib/prosopite.rb#178
    def mysql_fingerprint(query); end

    # source://prosopite//lib/prosopite.rb#76
    def pause; end

    # Sets the attribute prosopite_logger
    #
    # @param value the value to set the attribute prosopite_logger to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def prosopite_logger=(_arg0); end

    # Sets the attribute rails_logger
    #
    # @param value the value to set the attribute rails_logger to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def rails_logger=(_arg0); end

    # Sets the attribute raise
    #
    # @param value the value to set the attribute raise to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def raise=(_arg0); end

    # @return [Boolean]
    #
    # source://prosopite//lib/prosopite.rb#128
    def raise?; end

    # source://prosopite//lib/prosopite.rb#262
    def red(str); end

    # source://prosopite//lib/prosopite.rb#94
    def resume; end

    # source://prosopite//lib/prosopite.rb#43
    def scan; end

    # @return [Boolean]
    #
    # source://prosopite//lib/prosopite.rb#98
    def scan?; end

    # @raise [NPlusOneQueriesError]
    #
    # source://prosopite//lib/prosopite.rb#226
    def send_notifications; end

    # source://prosopite//lib/prosopite.rb#116
    def start_raise; end

    # Sets the attribute stderr_logger
    #
    # @param value the value to set the attribute stderr_logger to.
    #
    # source://prosopite//lib/prosopite.rb#10
    def stderr_logger=(_arg0); end

    # source://prosopite//lib/prosopite.rb#120
    def stop_raise; end

    # source://prosopite//lib/prosopite.rb#271
    def subscribe; end

    # source://prosopite//lib/prosopite.rb#72
    def tc; end
  end
end

# source://prosopite//lib/prosopite.rb#3
Prosopite::DEFAULT_ALLOW_LIST = T.let(T.unsafe(nil), Array)

# source://prosopite//lib/prosopite.rb#8
class Prosopite::NPlusOneQueriesError < ::StandardError; end
