// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import ClickController from "./click_controller";
import ClipboardController from "./clipboard_controller";
import DisabledController from "./disabled_controller";
import HelloController from "./hello_controller";
import IntersectionController from "./intersection_controller";
import MaintainScrollController from "./maintain_scroll_controller";
import ScrollToBottomController from "./scroll_to_bottom_controller";
import TooltipController from "./tooltip_controller";
// import LoremPicsumController from "./lorem_picsum_controller";

application.register("hello", HelloController);
application.register("tooltip", TooltipController);
application.register("scroll-to-bottom", ScrollToBottomController);
application.register("intersection", IntersectionController);
application.register("maintain-scroll", MaintainScrollController);
application.register("click", ClickController);
application.register("disabled", DisabledController);
application.register("clipboard", ClipboardController);
