# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveAgent::GenerationJob`.
# Please instead update this file by running `bin/tapioca dsl ActiveAgent::GenerationJob`.


class ActiveAgent::GenerationJob
  class << self
    sig do
      params(
        agent: T.untyped,
        agent_method: T.untyped,
        generation_method: T.untyped,
        args: T.untyped,
        kwargs: T.untyped,
        params: T.untyped,
        block: T.nilable(T.proc.params(job: ActiveAgent::GenerationJob).void)
      ).returns(T.any(ActiveAgent::GenerationJob, FalseClass))
    end
    def perform_later(agent, agent_method, generation_method, args:, kwargs: T.unsafe(nil), params: T.unsafe(nil), &block); end

    sig do
      params(
        agent: T.untyped,
        agent_method: T.untyped,
        generation_method: T.untyped,
        args: T.untyped,
        kwargs: T.untyped,
        params: T.untyped
      ).returns(T.untyped)
    end
    def perform_now(agent, agent_method, generation_method, args:, kwargs: T.unsafe(nil), params: T.unsafe(nil)); end
  end
end
