# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActualDbSchema::PhantomMigrationsController`.
# Please instead update this file by running `bin/tapioca dsl ActualDbSchema::PhantomMigrationsController`.


class ActualDbSchema::PhantomMigrationsController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::Turbo::DriveHelper
    include ::Turbo::FramesHelper
    include ::Turbo::IncludesHelper
    include ::Turbo::StreamsHelper
    include ::ActionView::Helpers::CaptureHelper
    include ::ActionView::Helpers::OutputSafetyHelper
    include ::ActionView::Helpers::TagHelper
    include ::Turbo::Streams::ActionHelper
    include ::ActionText::ContentHelper
    include ::ActionText::TagHelper
    include ::Lexxy::TagHelper
    include ::InertiaRails::Helper
    include ::InertiaRails::AssetHelper
    include ::ViteRails::TagHelpers
    include ::ActionController::Base::HelperMethods

    sig { returns(T.untyped) }
    def phantom_migration; end

    sig { returns(T.untyped) }
    def phantom_migrations; end
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
