# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-capybara

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - .github/**/*
    - .vscode/**/*
    - db/schema*.rb
    - public/**/*
    - storage/**/*
  CacheRootDirectory: tmp/cache/rubocop

Layout/ArgumentAlignment:
  Enabled: true
Layout/BlockAlignment:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
Layout/EndAlignment:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/HashAlignment:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/LineLength:
  Enabled: true
  Max: 80
Layout/MultilineArrayBraceLayout:
  Enabled: true
Layout/MultilineBlockLayout:
  Enabled: true
Layout/MultilineHashBraceLayout:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
Layout/MultilineMethodParameterLineBreaks:
  Enabled: true
Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/ParameterAlignment:
  Enabled: true
Layout/RescueEnsureAlignment:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceAfterMethodName:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma
