# fly.toml app configuration file generated for smallerworld on 2026-02-06T16:38:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smallerworld-v2"
primary_region = "iad"
console_command = "./bin/rails console"
swap_size_mb = 1024

[deploy]
strategy = "bluegreen"
release_command = "./bin/prepare-deployment"

[env]
CANONICAL_HOST = "app.smallerworld.club"
THRUSTER_HTTP_PORT = "8080"

[processes]
app = "./bin/thrust ./bin/rails server"
jobs = "./bin/jobs"

[http_service]
force_https = true
auto_stop_machines = "off"
auto_start_machines = false
processes = ["app"]

[[http_service.checks]]
interval = "10s"
timeout = "2s"
grace_period = "20s"
method = "GET"
path = "/up"
protocol = "http"

[[vm]]
processes = ["app"]
cpus = 1
memory_mb = 768

[[vm]]
name = ["jobs"]
cpu = 1
memory_mb = 512
