# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::DropdownMenu::Content`.
# Please instead update this file by running `bin/tapioca dsl Components::DropdownMenu::Content`.


class Components::DropdownMenu::Content
  sig { params(attributes: T.untyped, block: T.nilable(T.proc.void)).void }
  def el_menu(**attributes, &block); end
end
