# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::DropdownMenuContent`.
# Please instead update this file by running `bin/tapioca dsl Components::DropdownMenuContent`.


class Components::DropdownMenuContent
  sig { params(attributes: T.untyped, block: T.nilable(T.proc.void)).void }
  def el_menu(**attributes, &block); end
end
