/**
 * Generated by: GPT-5 Codex
 * Last modified: 2025-10-27 00:00:00 UTC
 *
 * This code was AI-generated and may require human review and testing.
 */
import {
  Box,
  Center,
  Group,
  Image,
  Radio,
  type RadioGroupProps,
} from "@mantine/core";
import { type FC } from "react";

import {
  useAvailableWorldThemes,
  worldThemeThumbnailSrc,
} from "~/helpers/worldThemes";
import { type WorldTheme } from "~/types";

import NoneIcon from "~icons/heroicons/no-symbol-20-solid";

import classes from "./WorldThemeRadioGroup.module.css";

export interface WorldThemeRadioGroupProps
  extends Omit<RadioGroupProps, "children"> {}

const WorldThemeRadioGroup: FC<WorldThemeRadioGroupProps> = ({
  ...otherProps
}) => {
  const availableThemes = useAvailableWorldThemes();
  return (
    <Radio.Group
      label="your world theme"
      labelProps={{ mb: 8 }}
      {...otherProps}
    >
      <Group justify="center" gap={6} wrap="wrap">
        <RadioCard worldTheme={null} />
        {availableThemes.map((worldTheme) => (
          <RadioCard key={worldTheme} {...{ worldTheme }} />
        ))}
      </Group>
    </Radio.Group>
  );
};

export default WorldThemeRadioGroup;

interface RadioCardProps {
  worldTheme: WorldTheme | null;
  imageSrc?: string;
}

const RadioCard: FC<RadioCardProps> = ({ worldTheme, imageSrc }) => (
  <Radio.Card className={classes.radioCard} value={worldTheme ?? ""}>
    {worldTheme ? (
      <Image
        src={imageSrc ?? worldThemeThumbnailSrc(worldTheme)}
        radius={1000}
        h="100%"
      />
    ) : (
      <Center className={classes.noTheme}>
        <Box component={NoneIcon} fz={24} c="dimmed" />
      </Center>
    )}
  </Radio.Card>
);
