# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveAgent::Providers::OpenRouter::Requests::Plugin`.
# Please instead update this file by running `bin/tapioca dsl ActiveAgent::Providers::OpenRouter::Requests::Plugin`.


class ActiveAgent::Providers::OpenRouter::Requests::Plugin
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    sig { returns(T.nilable(::String)) }
    def id; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def id=(value); end

    sig { returns(T.untyped) }
    def pdf; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def pdf=(value); end
  end
end
