# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AccountMailer`.
# Please instead update this file by running `bin/tapioca dsl AccountMailer`.


class AccountMailer
  class << self
    sig { params(user: ::User).returns(::ActionMailer::MessageDelivery) }
    def email_address_confirmation(user:); end
  end
end
