# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationAgent`.
# Please instead update this file by running `bin/tapioca dsl ApplicationAgent`.


class ApplicationAgent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
