# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ButtonLinkTo`.
# Please instead update this file by running `bin/tapioca dsl ButtonLinkTo`.


module ButtonLinkTo
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
