# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components`.
# Please instead update this file by running `bin/tapioca dsl Components`.


module Components
  sig do
    params(
      variant: ::Symbol,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Badge).void)
    ).void
  end
  def Badge(variant: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      variant: ::Symbol,
      size: ::Symbol,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Button).void)
    ).void
  end
  def Button(variant: T.unsafe(nil), size: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      size: ::Symbol,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Card).void)
    ).void
  end
  def Card(size: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      value: T.nilable(T.any(::ActiveStorage::Attachment, ::ActiveStorage::Blob)),
      field: T.nilable(::Symbol),
      direct_upload: T::Boolean,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::ClearableFileInput).void)
    ).void
  end
  def ClearableFileInput(form: T.unsafe(nil), value: T.unsafe(nil), field: T.unsafe(nil), direct_upload: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      clear_on_expand: T.nilable(T::Boolean),
      disabled: T::Boolean,
      default_value: T.nilable(::String),
      input: T::Hash[::Symbol, T.untyped],
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Combobox).void)
    ).void
  end
  def Combobox(form: T.unsafe(nil), field: T.unsafe(nil), clear_on_expand: T.unsafe(nil), disabled: T.unsafe(nil), default_value: T.unsafe(nil), input: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      anchor: T.any(::Symbol, T::Array[::Symbol]),
      anchor_strategy: T.nilable(::Symbol),
      popover: T::Boolean,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::ComboboxContent).void)
    ).void
  end
  def ComboboxContent(anchor:, anchor_strategy: T.unsafe(nil), popover: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::ComboboxList).void)
    ).void
  end
  def ComboboxList(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      id: ::String,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Dialog).void)
    ).void
  end
  def Dialog(id: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      dialog_id: ::String,
      show_close_button: T::Boolean,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::DialogContent).void)
    ).void
  end
  def DialogContent(dialog_id:, show_close_button: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::DialogHeader).void)
    ).void
  end
  def DialogHeader(element: T.unsafe(nil), **attributes, &block); end

  sig { params(attributes: T.untyped, block: T.nilable(T.proc.params(instance: Components::DropdownMenu).void)).void }
  def DropdownMenu(**attributes, &block); end

  sig do
    params(
      anchor: T.any(::Symbol, T::Array[::Symbol]),
      anchor_strategy: T.nilable(::Symbol),
      popover: T::Boolean,
      open: T::Boolean,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::DropdownMenuContent).void)
    ).void
  end
  def DropdownMenuContent(anchor:, anchor_strategy: T.unsafe(nil), popover: T.unsafe(nil), open: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      orientation: ::Symbol,
      invalid: T::Boolean,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Field).void)
    ).void
  end
  def Field(form: T.unsafe(nil), field: T.unsafe(nil), orientation: T.unsafe(nil), invalid: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::FieldGroup).void)
    ).void
  end
  def FieldGroup(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::FieldSet).void)
    ).void
  end
  def FieldSet(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::FileInput).void)
    ).void
  end
  def FileInput(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

  sig do
    params(
      attachment: ::ActiveStorage::Attachment,
      block: T.nilable(T.proc.params(instance: Components::FileItem).void)
    ).void
  end
  def FileItem(attachment:, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Header).void)
    ).void
  end
  def Header(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Input).void)
    ).void
  end
  def Input(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::InputGroup).void)
    ).void
  end
  def InputGroup(form: T.unsafe(nil), field: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      align: ::Symbol,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::InputGroupAddon).void)
    ).void
  end
  def InputGroupAddon(align:, **attributes, &block); end

  sig do
    params(
      variant: ::Symbol,
      size: ::Symbol,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Item).void)
    ).void
  end
  def Item(variant: T.unsafe(nil), size: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::ItemContent).void)
    ).void
  end
  def ItemContent(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::ItemGroup).void)
    ).void
  end
  def ItemGroup(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      site_title: T.nilable(::String),
      page_title: T.nilable(T.any(::String, T::Array[::String])),
      body_class: T.nilable(::String),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Layout).void)
    ).void
  end
  def Layout(site_title: T.unsafe(nil), page_title: T.unsafe(nil), body_class: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::LexxyEditor).void)
    ).void
  end
  def LexxyEditor(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

  sig do
    params(
      target: ::Object,
      pagy: T.nilable(::Pagy),
      autoclick: T::Boolean,
      disable_for: T.nilable(::ActiveSupport::Duration),
      variant: ::Symbol,
      size: ::Symbol,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::NextPageControl).void)
    ).void
  end
  def NextPageControl(target:, pagy:, autoclick: T.unsafe(nil), disable_for: T.unsafe(nil), variant: T.unsafe(nil), size: T.unsafe(nil), **options, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::PhoneNumberInput).void)
    ).void
  end
  def PhoneNumberInput(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

  sig do
    params(
      verification_request: ::PhoneNumberVerificationRequest,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::PhoneNumberVerificationRequestForm).void)
    ).void
  end
  def PhoneNumberVerificationRequestForm(verification_request:, **options, &block); end

  sig do
    params(
      post: ::Post,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::PostCard).void)
    ).void
  end
  def PostCard(post:, **attributes, &block); end

  sig do
    params(
      post: ::Post,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::PostForm).void)
    ).void
  end
  def PostForm(post:, **options, &block); end

  sig do
    params(
      orientation: ::Symbol,
      decorative: T::Boolean,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Separator).void)
    ).void
  end
  def Separator(orientation: T.unsafe(nil), decorative: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Spinner).void)
    ).void
  end
  def Spinner(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::PhlexFormBuilder),
      field: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Textarea).void)
    ).void
  end
  def Textarea(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

  sig do
    params(
      world: ::World,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::WorldForm).void)
    ).void
  end
  def WorldForm(world:, **options, &block); end

  sig do
    params(
      world: ::World,
      pagy: T.nilable(::Pagy),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::WorldNextPageControl).void)
    ).void
  end
  def WorldNextPageControl(world:, pagy:, **options, &block); end

  sig do
    params(
      posts: T::Enumerable[::Post],
      block: T.nilable(T.proc.params(instance: Components::WorldPostItems).void)
    ).void
  end
  def WorldPostItems(posts:, &block); end

  class << self
    sig do
      params(
        variant: ::Symbol,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Badge).void)
      ).void
    end
    def Badge(variant: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        variant: ::Symbol,
        size: ::Symbol,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Button).void)
      ).void
    end
    def Button(variant: T.unsafe(nil), size: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        size: ::Symbol,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Card).void)
      ).void
    end
    def Card(size: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        value: T.nilable(T.any(::ActiveStorage::Attachment, ::ActiveStorage::Blob)),
        field: T.nilable(::Symbol),
        direct_upload: T::Boolean,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::ClearableFileInput).void)
      ).void
    end
    def ClearableFileInput(form: T.unsafe(nil), value: T.unsafe(nil), field: T.unsafe(nil), direct_upload: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        clear_on_expand: T.nilable(T::Boolean),
        disabled: T::Boolean,
        default_value: T.nilable(::String),
        input: T::Hash[::Symbol, T.untyped],
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Combobox).void)
      ).void
    end
    def Combobox(form: T.unsafe(nil), field: T.unsafe(nil), clear_on_expand: T.unsafe(nil), disabled: T.unsafe(nil), default_value: T.unsafe(nil), input: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        anchor: T.any(::Symbol, T::Array[::Symbol]),
        anchor_strategy: T.nilable(::Symbol),
        popover: T::Boolean,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::ComboboxContent).void)
      ).void
    end
    def ComboboxContent(anchor:, anchor_strategy: T.unsafe(nil), popover: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::ComboboxList).void)
      ).void
    end
    def ComboboxList(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        id: ::String,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Dialog).void)
      ).void
    end
    def Dialog(id: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        dialog_id: ::String,
        show_close_button: T::Boolean,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::DialogContent).void)
      ).void
    end
    def DialogContent(dialog_id:, show_close_button: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::DialogHeader).void)
      ).void
    end
    def DialogHeader(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::DropdownMenu).void)
      ).void
    end
    def DropdownMenu(**attributes, &block); end

    sig do
      params(
        anchor: T.any(::Symbol, T::Array[::Symbol]),
        anchor_strategy: T.nilable(::Symbol),
        popover: T::Boolean,
        open: T::Boolean,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::DropdownMenuContent).void)
      ).void
    end
    def DropdownMenuContent(anchor:, anchor_strategy: T.unsafe(nil), popover: T.unsafe(nil), open: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        orientation: ::Symbol,
        invalid: T::Boolean,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Field).void)
      ).void
    end
    def Field(form: T.unsafe(nil), field: T.unsafe(nil), orientation: T.unsafe(nil), invalid: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::FieldGroup).void)
      ).void
    end
    def FieldGroup(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::FieldSet).void)
      ).void
    end
    def FieldSet(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::FileInput).void)
      ).void
    end
    def FileInput(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

    sig do
      params(
        attachment: ::ActiveStorage::Attachment,
        block: T.nilable(T.proc.params(instance: Components::FileItem).void)
      ).void
    end
    def FileItem(attachment:, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Header).void)
      ).void
    end
    def Header(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Input).void)
      ).void
    end
    def Input(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::InputGroup).void)
      ).void
    end
    def InputGroup(form: T.unsafe(nil), field: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        align: ::Symbol,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::InputGroupAddon).void)
      ).void
    end
    def InputGroupAddon(align:, **attributes, &block); end

    sig do
      params(
        variant: ::Symbol,
        size: ::Symbol,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Item).void)
      ).void
    end
    def Item(variant: T.unsafe(nil), size: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::ItemContent).void)
      ).void
    end
    def ItemContent(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::ItemGroup).void)
      ).void
    end
    def ItemGroup(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        site_title: T.nilable(::String),
        page_title: T.nilable(T.any(::String, T::Array[::String])),
        body_class: T.nilable(::String),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Layout).void)
      ).void
    end
    def Layout(site_title: T.unsafe(nil), page_title: T.unsafe(nil), body_class: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::LexxyEditor).void)
      ).void
    end
    def LexxyEditor(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

    sig do
      params(
        target: ::Object,
        pagy: T.nilable(::Pagy),
        autoclick: T::Boolean,
        disable_for: T.nilable(::ActiveSupport::Duration),
        variant: ::Symbol,
        size: ::Symbol,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::NextPageControl).void)
      ).void
    end
    def NextPageControl(target:, pagy:, autoclick: T.unsafe(nil), disable_for: T.unsafe(nil), variant: T.unsafe(nil), size: T.unsafe(nil), **options, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::PhoneNumberInput).void)
      ).void
    end
    def PhoneNumberInput(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

    sig do
      params(
        verification_request: ::PhoneNumberVerificationRequest,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::PhoneNumberVerificationRequestForm).void)
      ).void
    end
    def PhoneNumberVerificationRequestForm(verification_request:, **options, &block); end

    sig do
      params(
        post: ::Post,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::PostCard).void)
      ).void
    end
    def PostCard(post:, **attributes, &block); end

    sig do
      params(
        post: ::Post,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::PostForm).void)
      ).void
    end
    def PostForm(post:, **options, &block); end

    sig do
      params(
        orientation: ::Symbol,
        decorative: T::Boolean,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Separator).void)
      ).void
    end
    def Separator(orientation: T.unsafe(nil), decorative: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Spinner).void)
      ).void
    end
    def Spinner(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::PhlexFormBuilder),
        field: T.nilable(::Symbol),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Textarea).void)
      ).void
    end
    def Textarea(form: T.unsafe(nil), field: T.unsafe(nil), **options, &block); end

    sig do
      params(
        world: ::World,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::WorldForm).void)
      ).void
    end
    def WorldForm(world:, **options, &block); end

    sig do
      params(
        world: ::World,
        pagy: T.nilable(::Pagy),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::WorldNextPageControl).void)
      ).void
    end
    def WorldNextPageControl(world:, pagy:, **options, &block); end

    sig do
      params(
        posts: T::Enumerable[::Post],
        block: T.nilable(T.proc.params(instance: Components::WorldPostItems).void)
      ).void
    end
    def WorldPostItems(posts:, &block); end
  end
end
