# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components`.
# Please instead update this file by running `bin/tapioca dsl Components`.


module Components
  sig do
    params(
      variant: ::Symbol,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Badge).void)
    ).void
  end
  def Badge(variant: T.unsafe(nil), **options, &block); end

  sig do
    params(
      variant: ::Symbol,
      size: ::Symbol,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Button).void)
    ).void
  end
  def Button(variant: T.unsafe(nil), size: T.unsafe(nil), **options, &block); end

  sig do
    params(
      size: ::Symbol,
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Card).void)
    ).void
  end
  def Card(size: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      group: ::WhatsappGroup,
      messages: T::Array[::WhatsappMessage],
      pagy: T.nilable(::Pagy),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Chat).void)
    ).void
  end
  def Chat(group:, messages: T.unsafe(nil), pagy: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::Phlex::Rails::Builder),
      field: T.nilable(::Symbol),
      orientation: ::Symbol,
      invalid: T::Boolean,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Field).void)
    ).void
  end
  def Field(form: T.unsafe(nil), field: T.unsafe(nil), orientation: T.unsafe(nil), invalid: T.unsafe(nil), **options, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::FieldGroup).void)
    ).void
  end
  def FieldGroup(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::FieldSet).void)
    ).void
  end
  def FieldSet(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      element: T.nilable(::Symbol),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Header).void)
    ).void
  end
  def Header(element: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      form: T.nilable(::Phlex::Rails::Builder),
      field: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Input).void)
    ).void
  end
  def Input(form:, field: T.unsafe(nil), **options, &block); end

  sig do
    params(
      site_title: T.nilable(::String),
      page_title: T.nilable(T.any(::String, T::Array[::String])),
      body_class: T.nilable(::String),
      attributes: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Layout).void)
    ).void
  end
  def Layout(site_title: T.unsafe(nil), page_title: T.unsafe(nil), body_class: T.unsafe(nil), **attributes, &block); end

  sig do
    params(
      to: T.untyped,
      pagy: T.nilable(::Pagy),
      variant: ::Symbol,
      size: ::Symbol,
      form_class: T.nilable(::String),
      form: T::Hash[::Symbol, T.untyped],
      disable_for: T.nilable(::ActiveSupport::Duration),
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::PaginationButton).void)
    ).void
  end
  def PaginationButton(to:, pagy: T.unsafe(nil), variant: T.unsafe(nil), size: T.unsafe(nil), form_class: T.unsafe(nil), form: T.unsafe(nil), disable_for: T.unsafe(nil), **options, &block); end

  sig do
    params(
      orientation: ::Symbol,
      decorative: T::Boolean,
      options: T.untyped,
      block: T.nilable(T.proc.params(instance: Components::Separator).void)
    ).void
  end
  def Separator(orientation: T.unsafe(nil), decorative: T.unsafe(nil), **options, &block); end

  class << self
    sig do
      params(
        variant: ::Symbol,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Badge).void)
      ).void
    end
    def Badge(variant: T.unsafe(nil), **options, &block); end

    sig do
      params(
        variant: ::Symbol,
        size: ::Symbol,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Button).void)
      ).void
    end
    def Button(variant: T.unsafe(nil), size: T.unsafe(nil), **options, &block); end

    sig do
      params(
        size: ::Symbol,
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Card).void)
      ).void
    end
    def Card(size: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        group: ::WhatsappGroup,
        messages: T::Array[::WhatsappMessage],
        pagy: T.nilable(::Pagy),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Chat).void)
      ).void
    end
    def Chat(group:, messages: T.unsafe(nil), pagy: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::Phlex::Rails::Builder),
        field: T.nilable(::Symbol),
        orientation: ::Symbol,
        invalid: T::Boolean,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Field).void)
      ).void
    end
    def Field(form: T.unsafe(nil), field: T.unsafe(nil), orientation: T.unsafe(nil), invalid: T.unsafe(nil), **options, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::FieldGroup).void)
      ).void
    end
    def FieldGroup(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::FieldSet).void)
      ).void
    end
    def FieldSet(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        element: T.nilable(::Symbol),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Header).void)
      ).void
    end
    def Header(element: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        form: T.nilable(::Phlex::Rails::Builder),
        field: T.nilable(::Symbol),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Input).void)
      ).void
    end
    def Input(form:, field: T.unsafe(nil), **options, &block); end

    sig do
      params(
        site_title: T.nilable(::String),
        page_title: T.nilable(T.any(::String, T::Array[::String])),
        body_class: T.nilable(::String),
        attributes: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Layout).void)
      ).void
    end
    def Layout(site_title: T.unsafe(nil), page_title: T.unsafe(nil), body_class: T.unsafe(nil), **attributes, &block); end

    sig do
      params(
        to: T.untyped,
        pagy: T.nilable(::Pagy),
        variant: ::Symbol,
        size: ::Symbol,
        form_class: T.nilable(::String),
        form: T::Hash[::Symbol, T.untyped],
        disable_for: T.nilable(::ActiveSupport::Duration),
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::PaginationButton).void)
      ).void
    end
    def PaginationButton(to:, pagy: T.unsafe(nil), variant: T.unsafe(nil), size: T.unsafe(nil), form_class: T.unsafe(nil), form: T.unsafe(nil), disable_for: T.unsafe(nil), **options, &block); end

    sig do
      params(
        orientation: ::Symbol,
        decorative: T::Boolean,
        options: T.untyped,
        block: T.nilable(T.proc.params(instance: Components::Separator).void)
      ).void
    end
    def Separator(orientation: T.unsafe(nil), decorative: T.unsafe(nil), **options, &block); end
  end
end
