# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PasswordsMailer`.
# Please instead update this file by running `bin/tapioca dsl PasswordsMailer`.


class PasswordsMailer
  class << self
    sig { params(user: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def reset(user); end

    sig { returns(::ActionMailer::MessageDelivery) }
    def roadie_options; end
  end
end
