# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PurgeUnattachedActiveStorageBlobsJob`.
# Please instead update this file by running `bin/tapioca dsl PurgeUnattachedActiveStorageBlobsJob`.


class PurgeUnattachedActiveStorageBlobsJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: PurgeUnattachedActiveStorageBlobsJob).void)
      ).returns(T.any(PurgeUnattachedActiveStorageBlobsJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
