# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SendUserBadgeCountNotificationsJob`.
# Please instead update this file by running `bin/tapioca dsl SendUserBadgeCountNotificationsJob`.


class SendUserBadgeCountNotificationsJob
  class << self
    sig do
      params(
        user: ::User,
        block: T.nilable(T.proc.params(job: SendUserBadgeCountNotificationsJob).void)
      ).returns(T.any(SendUserBadgeCountNotificationsJob, FalseClass))
    end
    def perform_later(user, &block); end

    sig { params(user: ::User).void }
    def perform_now(user); end
  end
end
