# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TriggerWorldCardPassUpdateJob`.
# Please instead update this file by running `bin/tapioca dsl TriggerWorldCardPassUpdateJob`.


class TriggerWorldCardPassUpdateJob
  class << self
    sig do
      params(
        world_card: ::WorldCard,
        block: T.nilable(T.proc.params(job: TriggerWorldCardPassUpdateJob).void)
      ).returns(T.any(TriggerWorldCardPassUpdateJob, FalseClass))
    end
    def perform_later(world_card, &block); end

    sig { params(world_card: ::WorldCard).void }
    def perform_now(world_card); end
  end
end
