# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UrlHelpers`.
# Please instead update this file by running `bin/tapioca dsl UrlHelpers`.


class UrlHelpers
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
