# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldKeyGrant`.
# Please instead update this file by running `bin/tapioca dsl WorldKeyGrant`.


class WorldKeyGrant
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    sig { returns(T.untyped) }
    def granted_post_type_ids; end

    sig { params(value: T.untyped).returns(T.untyped) }
    def granted_post_type_ids=(value); end
  end
end
