# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveAgent::Providers::OpenRouter::Requests::Plugins::PdfConfig`.
# Please instead update this file by running `bin/tapioca dsl ActiveAgent::Providers::OpenRouter::Requests::Plugins::PdfConfig`.


class ActiveAgent::Providers::OpenRouter::Requests::Plugins::PdfConfig
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    sig { returns(T.nilable(::String)) }
    def engine; end

    sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
    def engine=(value); end
  end
end
