# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AfterAttached::AttachmentCallbacks`.
# Please instead update this file by running `bin/tapioca dsl AfterAttached::AttachmentCallbacks`.


module AfterAttached::AttachmentCallbacks
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def _attachment_callbacks; end
    def _attachment_callbacks=(value); end
    def _attachment_callbacks?; end
  end

  module GeneratedInstanceMethods
    def _attachment_callbacks; end
    def _attachment_callbacks=(value); end
    def _attachment_callbacks?; end
  end
end
