shared:
  # Use bin/rails credentials:edit to set the apns secrets (as action_push_native:apns:key_id|encryption_key)
  apple:
    # Token auth params
    # See https://developer.apple.com/documentation/usernotifications/establishing-a-token-based-connection-to-apns
    key_id: <%= Rails.application.credentials.dig(:action_push_native, :apns, :key_id) %>
    encryption_key: <%= Rails.application.credentials.dig(:action_push_native, :apns, :encryption_key)&.dump %>

    team_id: UB3SB3746X
    # Your identifier found on
    # https://developer.apple.com/account/resources/identifiers/list
    topic: club.smallerworld.app

    # Set this to the number of threads used to process notifications (default: 5).
    # When the pool size is too small a HTTPX::PoolTimeoutError error will be raised.
    # connection_pool_size: 5

    # Change the request timeout (default: 30).
    # request_timeout: 60

    # Decide when to connect to APNs development server.
    # Please note that anything built directly from Xcode and loaded on your phone will have
    # the app generate DEVELOPMENT tokens, while everything else (TestFlight, Apple Store, ...)
    # will be considered as PRODUCTION environment.
    # connect_to_development_server: <%# Rails.env.development? %>

  # Use bin/rails credentials:edit to set the fcm secrets (as action_push_native:fcm:encryption_key)
  google:
    # Your Firebase project service account credentials
    # See https://firebase.google.com/docs/cloud-messaging/auth-server
    encryption_key: <%= Rails.application.credentials.dig(:action_push_native, :fcm, :encryption_key)&.dump %>

    # Firebase project_id
    project_id: your_project_id

    # Set this to the number of threads used to process notifications (default: 5).
    # When the pool size is too small a HTTPX::PoolTimeoutError error will be raised.
    # connection_pool_size: 5

    # Change the request timeout (default: 15).
    # request_timeout: 30
