# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

shared: &shared
  clear_solid_queue_finished_jobs:
    class: ClearFinishedSolidQueueJobsJob
    schedule: every hour at minute 12
  purge_unattached_active_storage_blobs:
    class: PurgeUnattachedActiveStorageBlobsJob
    schedule: every 6 hours at minute 17
  clear_orphaned_passkit_devices:
    class: ClearOrphanedPasskitDevicesJob
    schedule: every day at 3:13am
  clear_old_passkit_logs:
    class: ClearOldPasskitLogsJob
    schedule: every day at 3:23am
  clear_unregistered_world_cards:
    class: ClearUnregisteredWorldCardsJob
    schedule: every day at 3:17am

development:
  <<: *shared

production:
  <<: *shared
