inherit_from: ../../.rubocop.yml

plugins:
  - rubocop-sorbet

AllCops:
  Exclude:
    - annotations/**/*
    - dsl/**/*
    - gems/**/*

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
